#!/bin/bash

distdir=`cat RPMNAME`
archive=$distdir-`cat VERSION`.tar.bz2

mkdir $distdir

cp -r src/* $distdir

tar cjf $archive $distdir --exclude .cvsignore --exclude CVS

rm -r $distdir

rm -f package/*.tar.bz2
mv $archive package
