#!/usr/bin/perl

$version = `cat VERSION`;

$version =~ s/\n//g;
$version =~ s/\./_/g;
$tag = "stable-" . $version;

print "TAG: $tag\n";

my $dontTag = 0;

print "cvs update...\n";

if ( !open UP, "cvs up|" ) {
  print STDERR "Unable to 'cvs up'.\n";
  exit 1;
} else {
  while ( <UP> ) {
    print;
    if ( /^M/ ) {
      $dontTag = 1;
    }
  }
}

if ( $dontTag ) {
  print STDERR "Locally modified files found. Abort tagging.\n";
  exit 1;
}

print "Tagging...\n";

system( "cvs tag $tag" );
